---

# Add apt-key and repository
- name: Add postgresql apt-key
  apt_key: 
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present

- name: Add postgresql repository
  apt_repository:
    repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    state=present

# Install
- name: Install postgresql-9.5 and dependency
  apt:
    name={{ item }}
    state=present
    install_recommends=yes
  with_items:
    - postgresql-9.5
    - postgresql-common
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - iputils-arping
#    - arping
