---

# Update and upgrade system
- name: Update ubuntu server
  apt:
    update_cache=yes
    upgrade=dist


- name: Set the fr locale
  shell: locale-gen fr_FR.UTF-8

- name: Reconfigure locales
  shell: dpkg-reconfigure locales


- name: install basics
  apt:
    name={{ item }}
    state=latest
  with_items:
    - git
    - git-core
    - zsh
    - ufw
    - ssh



# Install zsh and oh my zsh
- name: Install oh my zsh for root user
  git:
    repo=git://github.com/robbyrussell/oh-my-zsh.git
    dest=/root/.oh-my-zsh
    accept_hostkey=yes

- name: Configure zsh for root user
  copy:
    src={{ item.source }}
    dest={{ item.dest }}
  with_items:
  - {source: 'webinage.zsh-theme', dest: '/root/.oh-my-zsh/themes/webinage.zsh-theme'}
  - {source: 'zshrc', dest: '/root/.zshrc'}

- name: Change default shell for root
  user:
    name=root
    shell=/bin/zsh



# Configure firewall
- name: Allow new firewall rules
  ufw: rule=allow src={{ item }}
  with_items:
  - "{{ ip_prod1 }}"
  - "{{ ip_prod2 }}"
  - "{{ ip_virtual }}"


- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false

